<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class TouchPointSeeder extends Seeder {
    public function run(): void {
        DB::table('touch_points')->insert([
            [
                'id'                     => 1,
                'user_id'                => 3,
                'is_completed'           => 1,
                'avatar'                 => null,
                'name'                   => 'First Red',
                'phone_number'           => '+123456789',
                'contact_type'           => 'personal',
                'contact_method'         => 'call',
                'touch_point_start_date' => '2025-04-24',
                'touch_point_start_time' => '21:25:00',
                'frequency'              => 'monthly',
                'custom_days'            => null,
                'notes'                  => 'Follow up in 20 days',
                'status'                 => 'active',
                'created_at'             => Carbon::parse('2025-04-27 00:35:23'),
                'updated_at'             => Carbon::parse('2025-04-30 05:24:07'),
                'deleted_at'             => null,
            ],
            [
                'id'                     => 2,
                'user_id'                => 3,
                'is_completed'           => 1,
                'avatar'                 => null,
                'name'                   => 'First Blue',
                'phone_number'           => '+123456789',
                'contact_type'           => 'personal',
                'contact_method'         => 'text',
                'touch_point_start_date' => '2025-04-27',
                'touch_point_start_time' => '21:25:00',
                'frequency'              => 'monthly',
                'custom_days'            => null,
                'notes'                  => 'Follow up in 20 days',
                'status'                 => 'active',
                'created_at'             => Carbon::parse('2025-04-27 00:36:12'),
                'updated_at'             => Carbon::parse('2025-04-30 05:24:19'),
                'deleted_at'             => null,
            ],
            [
                'id'                     => 3,
                'user_id'                => 3,
                'is_completed'           => 1,
                'avatar'                 => null,
                'name'                   => 'First Yellow',
                'phone_number'           => '+123456789',
                'contact_type'           => 'personal',
                'contact_method'         => 'meetup',
                'touch_point_start_date' => '2025-04-28',
                'touch_point_start_time' => '21:25:00',
                'frequency'              => 'monthly',
                'custom_days'            => null,
                'notes'                  => 'Follow up in 20 days',
                'status'                 => 'active',
                'created_at'             => Carbon::parse('2025-04-27 00:36:33'),
                'updated_at'             => Carbon::parse('2025-04-30 05:24:36'),
                'deleted_at'             => null,
            ],
            [
                'id'                     => 4,
                'user_id'                => 3,
                'is_completed'           => 0,
                'avatar'                 => null,
                'name'                   => 'First Green',
                'phone_number'           => '+123456789',
                'contact_type'           => 'personal',
                'contact_method'         => 'call',
                'touch_point_start_date' => '2025-04-30',
                'touch_point_start_time' => '21:25:00',
                'frequency'              => 'monthly',
                'custom_days'            => null,
                'notes'                  => 'Follow up in 20 days',
                'status'                 => 'active',
                'created_at'             => Carbon::parse('2025-04-27 00:36:48'),
                'updated_at'             => Carbon::parse('2025-04-27 00:36:48'),
                'deleted_at'             => null,
            ],
            [
                'id'                     => 5,
                'user_id'                => 3,
                'is_completed'           => 0,
                'avatar'                 => null,
                'name'                   => 'Second Red',
                'phone_number'           => '+123456789',
                'contact_type'           => 'business',
                'contact_method'         => 'call',
                'touch_point_start_date' => '2025-04-25',
                'touch_point_start_time' => '21:25:00',
                'frequency'              => 'monthly',
                'custom_days'            => null,
                'notes'                  => 'Follow up in 10 days',
                'status'                 => 'active',
                'created_at'             => Carbon::parse('2025-04-27 00:52:51'),
                'updated_at'             => Carbon::parse('2025-04-27 00:53:12'),
                'deleted_at'             => null,
            ],
            [
                'id'                     => 6,
                'user_id'                => 3,
                'is_completed'           => 0,
                'avatar'                 => null,
                'name'                   => 'Second Blue',
                'phone_number'           => '+123456789',
                'contact_type'           => 'business',
                'contact_method'         => 'text',
                'touch_point_start_date' => '2025-04-27',
                'touch_point_start_time' => '21:25:00',
                'frequency'              => 'monthly',
                'custom_days'            => null,
                'notes'                  => 'Follow up in 10 days',
                'status'                 => 'active',
                'created_at'             => Carbon::parse('2025-04-27 00:53:37'),
                'updated_at'             => Carbon::parse('2025-04-27 00:57:39'),
                'deleted_at'             => null,
            ],
            [
                'id'                     => 7,
                'user_id'                => 3,
                'is_completed'           => 0,
                'avatar'                 => null,
                'name'                   => 'Second Yellow',
                'phone_number'           => '+123456789',
                'contact_type'           => 'business',
                'contact_method'         => 'meetup',
                'touch_point_start_date' => '2025-04-28',
                'touch_point_start_time' => '20:25:00',
                'frequency'              => 'monthly',
                'custom_days'            => null,
                'notes'                  => 'Follow up in 10 days',
                'status'                 => 'active',
                'created_at'             => Carbon::parse('2025-04-27 00:54:09'),
                'updated_at'             => Carbon::parse('2025-04-27 00:57:44'),
                'deleted_at'             => null,
            ],
            [
                'id'                     => 8,
                'user_id'                => 3,
                'is_completed'           => 0,
                'avatar'                 => null,
                'name'                   => 'Second Green',
                'phone_number'           => '+123456789',
                'contact_type'           => 'business',
                'contact_method'         => 'call',
                'touch_point_start_date' => '2025-04-29',
                'touch_point_start_time' => '21:25:00',
                'frequency'              => 'monthly',
                'custom_days'            => null,
                'notes'                  => 'Follow up in 10 days',
                'status'                 => 'active',
                'created_at'             => Carbon::parse('2025-04-27 00:54:30'),
                'updated_at'             => Carbon::parse('2025-04-27 00:57:00'),
                'deleted_at'             => null,
            ],
            [
                'id'                     => 9,
                'user_id'                => 3,
                'is_completed'           => 0,
                'avatar'                 => null,
                'name'                   => 'Autumn Phillips',
                'phone_number'           => '+1234567890',
                'contact_type'           => 'personal',
                'contact_method'         => 'text',
                'touch_point_start_date' => '2025-05-03',
                'touch_point_start_time' => '23:25:00',
                'frequency'              => 'custom',
                'custom_days'            => 15,
                'notes'                  => 'Follow up in 15 days',
                'status'                 => 'active',
                'created_at'             => Carbon::parse('2025-04-30 05:28:57'),
                'updated_at'             => Carbon::parse('2025-04-30 05:28:57'),
                'deleted_at'             => null,
            ],
        ]);
    }
}
