<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TouchPointSeeder extends Seeder {
    public function run(): void {
        DB::table('touch_points')->insert([
            [
                'id'                     => 1,
                'user_id'                => 3,
                'avatar'                 => null,
                'name'                   => 'First Red',
                'phone_number'           => '+123456789',
                'contact_type'           => 'personal',
                'contact_method'         => 'call',
                'touch_point_start_date' => '2025-04-24',
                'touch_point_start_time' => '21:25:00',
                'frequency'              => 'monthly',
                'custom_days'            => null,
                'notes'                  => 'Follow up in 20 days',
                'status'                 => 'active',
                'created_at'             => '2025-04-27 06:35:23',
                'updated_at'             => '2025-04-27 06:35:49',
                'deleted_at'             => null,
            ],
            [
                'id'                     => 2,
                'user_id'                => 3,
                'avatar'                 => null,
                'name'                   => 'First Blue',
                'phone_number'           => '+123456789',
                'contact_type'           => 'personal',
                'contact_method'         => 'text',
                'touch_point_start_date' => '2025-04-27',
                'touch_point_start_time' => '21:25:00',
                'frequency'              => 'monthly',
                'custom_days'            => null,
                'notes'                  => 'Follow up in 20 days',
                'status'                 => 'active',
                'created_at'             => '2025-04-27 06:36:12',
                'updated_at'             => '2025-04-27 06:47:00',
                'deleted_at'             => null,
            ],
            [
                'id'                     => 3,
                'user_id'                => 3,
                'avatar'                 => null,
                'name'                   => 'First Yellow',
                'phone_number'           => '+123456789',
                'contact_type'           => 'personal',
                'contact_method'         => 'meetup',
                'touch_point_start_date' => '2025-04-28',
                'touch_point_start_time' => '21:25:00',
                'frequency'              => 'monthly',
                'custom_days'            => null,
                'notes'                  => 'Follow up in 20 days',
                'status'                 => 'active',
                'created_at'             => '2025-04-27 06:36:33',
                'updated_at'             => '2025-04-27 06:47:03',
                'deleted_at'             => null,
            ],
            [
                'id'                     => 4,
                'user_id'                => 3,
                'avatar'                 => null,
                'name'                   => 'First Green',
                'phone_number'           => '+123456789',
                'contact_type'           => 'personal',
                'contact_method'         => 'call',
                'touch_point_start_date' => '2025-04-30',
                'touch_point_start_time' => '21:25:00',
                'frequency'              => 'monthly',
                'custom_days'            => null,
                'notes'                  => 'Follow up in 20 days',
                'status'                 => 'active',
                'created_at'             => '2025-04-27 06:36:48',
                'updated_at'             => '2025-04-27 06:36:48',
                'deleted_at'             => null,
            ],
            [
                'id'                     => 5,
                'user_id'                => 3,
                'avatar'                 => null,
                'name'                   => 'Second Red',
                'phone_number'           => '+123456789',
                'contact_type'           => 'business',
                'contact_method'         => 'call',
                'touch_point_start_date' => '2025-04-25',
                'touch_point_start_time' => '21:25:00',
                'frequency'              => 'monthly',
                'custom_days'            => null,
                'notes'                  => 'Follow up in 10 days',
                'status'                 => 'active',
                'created_at'             => '2025-04-27 06:52:51',
                'updated_at'             => '2025-04-27 06:53:12',
                'deleted_at'             => null,
            ],
            [
                'id'                     => 6,
                'user_id'                => 3,
                'avatar'                 => null,
                'name'                   => 'Second Blue',
                'phone_number'           => '+123456789',
                'contact_type'           => 'business',
                'contact_method'         => 'text',
                'touch_point_start_date' => '2025-04-27',
                'touch_point_start_time' => '21:25:00',
                'frequency'              => 'monthly',
                'custom_days'            => null,
                'notes'                  => 'Follow up in 10 days',
                'status'                 => 'active',
                'created_at'             => '2025-04-27 06:53:37',
                'updated_at'             => '2025-04-27 06:57:39',
                'deleted_at'             => null,
            ],
            [
                'id'                     => 7,
                'user_id'                => 3,
                'avatar'                 => null,
                'name'                   => 'Second Yellow',
                'phone_number'           => '+123456789',
                'contact_type'           => 'business',
                'contact_method'         => 'meetup',
                'touch_point_start_date' => '2025-04-28',
                'touch_point_start_time' => '20:25:00',
                'frequency'              => 'monthly',
                'custom_days'            => null,
                'notes'                  => 'Follow up in 10 days',
                'status'                 => 'active',
                'created_at'             => '2025-04-27 06:54:09',
                'updated_at'             => '2025-04-27 06:57:44',
                'deleted_at'             => null,
            ],
            [
                'id'                     => 8,
                'user_id'                => 3,
                'avatar'                 => null,
                'name'                   => 'Second Green',
                'phone_number'           => '+123456789',
                'contact_type'           => 'business',
                'contact_method'         => 'call',
                'touch_point_start_date' => '2025-04-29',
                'touch_point_start_time' => '21:25:00',
                'frequency'              => 'monthly',
                'custom_days'            => null,
                'notes'                  => 'Follow up in 10 days',
                'status'                 => 'active',
                'created_at'             => '2025-04-27 06:54:30',
                'updated_at'             => '2025-04-27 06:57:00',
                'deleted_at'             => null,
            ],
        ]);
    }
}
